spring:
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9094}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
    listener:
      concurrency: 1

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always # on-param
    include-stacktrace: on_param

iasmin:
  pabx:
    url: ${IASMIN_PABX_URL:http://localhost:8080}
  backend:
    url: ${IASMIN_BACKEND_URL:http://localhost:8081}

whisper:
  command: ${WHISPER_COMMAND:whisper}
  audios: ${WHISPER_AUDIOS:audio}
  transcripts: ${WHISPER_TRANSCRIPTS:transcripts}

kafka:
  topic: ${KAFKA_TOPIC:whisper}